import type { ReusableCapabilityAssessment } from "./types";

export const researchAutomationCapabilityAssessments: ReusableCapabilityAssessment[] =
  [
    {
      id: "agent-factory-mock-workflow",
      name: "Agent Factory mock workflow",
      source: "agent_factory",
      status: "reusable_now",
      license: "internal",
      maintenanceSignal: "当前仓库内维护，已纳入 pnpm check。",
      useCase: "先跑通采集计划、mock 采集、建库和报告输出。",
      reason: "符合第一版不接真实 API、不写密钥、不抓真实网页的约束。",
    },
    {
      id: "openai-compatible-llm-provider",
      name: "9router / OpenAI-compatible provider",
      source: "future_plugin",
      status: "future_candidate",
      license: "provider-api",
      maintenanceSignal:
        "本项目通过服务端 OpenAI-compatible chat/completions 调用结构化抽取和报告节点；当前 free provider 需逐次实测。",
      useCase:
        "把公开采集 raw documents 和行业研究数据库视图抽取成结构化结果，并生成 Markdown 报告。",
      reason:
        "只在服务端读取环境变量并调用文本模型，不把 API Key 暴露给前端；生产或付费交付必须切自付费 provider。",
    },
    {
      id: "hermes-xcrawl",
      name: "Hermes XCrawl skill",
      source: "hermes",
      status: "future_candidate",
      license: "MIT",
      maintenanceSignal:
        "本机 Hermes skills 中存在，支持 scrape/search/crawl/map。",
      useCase: "后续接公开网页、RSS、站点地图和竞品页面抓取。",
      reason: "需要 API key；本轮不能接真实密钥，所以只记录为未来候选。",
    },
    {
      id: "hermes-blogwatcher",
      name: "Hermes Blogwatcher skill",
      source: "hermes",
      status: "future_candidate",
      license: "MIT",
      maintenanceSignal:
        "本机 Hermes skills 中存在，支持 RSS/Atom feed 监控和 feed 自动发现；当前系统提示 blogwatcher-cli 尚未安装。",
      useCase: "后续为行业情报周报建立 RSS/Atom 监控库。",
      reason:
        "非常适合周报型数据库，但需要安装 CLI；本轮先在 TypeScript 包内建立公开 RSS adapter 边界。",
      url: "https://github.com/JulienTant/blogwatcher-cli",
    },
    {
      id: "hermes-tavily-search",
      name: "Hermes Tavily search skill",
      source: "hermes",
      status: "reusable_now",
      license: "provider-api",
      maintenanceSignal:
        "本机 Hermes skills 中存在，支持 search/extract/map/crawl/research；核心 workflow 已接入 Tavily Search API 作为候选 URL 发现 provider。",
      useCase:
        "用于陌生行业的信息源发现；extract/map/crawl/research 仍先不接入核心 workflow。",
      reason:
        "依赖 Tavily API Key；Search endpoint 返回结构稳定，适合替代 DDG HTML 做候选公开 URL 发现。",
    },
    {
      id: "hermes-camofox",
      name: "Hermes Camofox browser",
      source: "hermes",
      status: "future_candidate",
      license: "MIT",
      maintenanceSignal:
        "本机 Hermes tools 中存在，适合需要浏览器渲染的公开页面。",
      useCase: "后续处理 JS 较重页面、需要浏览器快照的页面抽取。",
      reason:
        "涉及浏览器会话、cookies 和更高合规风险；第一版不绕过登录、验证码或付费墙。",
    },
    {
      id: "openclaw-scrapling",
      name: "OpenClaw Scrapling stack",
      source: "openclaw",
      status: "future_candidate",
      license: "library-dependent",
      maintenanceSignal:
        "本机 OpenClaw venv 中存在 scrapling、beautifulsoup4、lxml、curl_cffi 和 protego。",
      useCase: "后续做 Python 侧公开网页正文抽取和 robots 规则检查。",
      reason: "当前项目主栈是 TypeScript；本轮不新增跨语言运行链路。",
    },
    {
      id: "github-apify-crawlee",
      name: "apify/crawlee",
      source: "github",
      status: "future_candidate",
      license: "Apache-2.0",
      maintenanceSignal: "GitHub 搜索显示 23680 stars，2026-06-05 仍更新。",
      useCase: "后续 TypeScript 真实 crawler、队列、浏览器或 Cheerio 抽取。",
      reason:
        "能力匹配但依赖和运行复杂度高；本轮只做 mock crawler，不直接引入。",
      url: "https://github.com/apify/crawlee",
    },
    {
      id: "github-rss-parser",
      name: "rbren/rss-parser",
      source: "github",
      status: "future_candidate",
      license: "MIT",
      maintenanceSignal:
        "GitHub README 显示它是把 RSS XML feed 转成 JavaScript objects 的轻量库。",
      useCase: "后续替换当前轻量 RSS XML 解析逻辑，提升 RSS/Atom 兼容性。",
      reason: "第一版 adapter 不引入依赖；等真实 RSS 源数量上来后再引入更稳。",
      url: "https://github.com/rbren/rss-parser",
    },
    {
      id: "github-mozilla-readability",
      name: "mozilla/readability",
      source: "github",
      status: "future_candidate",
      license: "Apache-2.0",
      maintenanceSignal:
        "Mozilla 官方仓库，README 说明 Node.js 场景需要搭配 DOM 实现。",
      useCase: "后续替换当前轻量 HTML 文本抽取逻辑，生成更干净的正文。",
      reason: "需要额外 DOM 依赖；当前先不增加包体和安装复杂度。",
      url: "https://github.com/mozilla/readability",
    },
    {
      id: "github-sitemapper",
      name: "seantomburke/sitemapper",
      source: "github",
      status: "future_candidate",
      license: "MIT",
      maintenanceSignal:
        "GitHub README 显示它支持单个 sitemap、sitemap index 和多种 sitemap 格式。",
      useCase: "后续替换当前轻量 sitemap `<loc>` 提取逻辑。",
      reason: "当前只需要最小公开 sitemap 抽取；复杂 sitemap index 后续再接。",
      url: "https://github.com/seantomburke/sitemapper",
    },
    {
      id: "github-firecrawl",
      name: "firecrawl/firecrawl",
      source: "github",
      status: "not_selected",
      license: "AGPL-3.0",
      maintenanceSignal: "GitHub 搜索显示 129008 stars，2026-06-05 仍更新。",
      useCase: "网页搜索、抓取、正文转 Markdown。",
      reason: "能力强但 AGPL 和外部服务边界需要单独评估；本轮不引入。",
      url: "https://github.com/firecrawl/firecrawl",
    },
    {
      id: "github-rss-mcp",
      name: "veithly/rss-mcp",
      source: "github",
      status: "future_candidate",
      license: "Apache-2.0",
      maintenanceSignal: "GitHub 搜索显示 2026-06-02 仍更新。",
      useCase: "后续 RSS/Atom feed 解析和 RSSHub 支持。",
      reason: "当前第一版只需要记录 RSS 采集计划，不需要真实 MCP 接入。",
      url: "https://github.com/veithly/rss-mcp",
    },
    {
      id: "github-feedfinder",
      name: "0x2E/feedfinder-ts",
      source: "github",
      status: "future_candidate",
      license: "MIT",
      maintenanceSignal: "GitHub 搜索显示 2026-02-26 更新，但 stars 较少。",
      useCase: "从网站 URL 自动发现 RSS/Atom feed。",
      reason: "轻量但成熟度信号弱；先记录，真实接入前再验证。",
      url: "https://github.com/0x2E/feedfinder-ts",
    },
    {
      id: "github-html-readability",
      name: "TechupBusiness/n8n-nodes-html-readability",
      source: "github",
      status: "future_candidate",
      license: "MIT",
      maintenanceSignal: "GitHub 搜索显示 2026-05-11 更新。",
      useCase: "n8n 中用 Mozilla Readability 抽取网页正文。",
      reason: "适合未来 n8n 真实流程；本轮只更新 n8n 草案。",
      url: "https://github.com/TechupBusiness/n8n-nodes-html-readability",
    },
    {
      id: "github-n8n-templates",
      name: "enescingoz/awesome-n8n-templates",
      source: "github",
      status: "future_candidate",
      license: "Other",
      maintenanceSignal: "GitHub 搜索显示 22721 stars，2026-06-05 仍更新。",
      useCase: "参考 n8n 自动化模板结构。",
      reason: "模板质量和 license 不统一；当前只参考思路，不复制模板内容。",
      url: "https://github.com/enescingoz/awesome-n8n-templates",
    },
  ];
